project:
  type: website

website:
  title: "Antonio Carlos Rodrigues"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with R and Quarto"
  navbar:
    left:
      - href: blog/index.qmd
      - href: teaching/index.qmd
      - href: publications.qmd
format:
  html:
    theme: [cosmo, styles.scss]

